import React from "react";
import { useMemo, useState } from "react";
import { CheckCircle2, XCircle, UserRound, FileText, ChevronRight } from "lucide-react";
import { calculateMatchScore, useApp } from "../context/AppContext";
import { Badge, Button, Card, Modal, ScoreRing, SearchInput } from "../components/UI";

export function BrowseJobs() {
  const { jobs, applications, createApplication, user } = useApp(); const [q, setQ] = useState(""); const [selected, setSelected] = useState(null); const [step, setStep] = useState(1); const [answers, setAnswers] = useState(["", ""]); const [message, setMessage] = useState("");
  const list = jobs.filter(j => !["Closed", "Paused", "Draft"].includes(j.status) && !j.archived).filter(j => `${j.title} ${j.department} ${j.location}`.toLowerCase().includes(q.toLowerCase()));
  const openApply = j => { setSelected(j); setStep(1); setMessage(""); };
  const submit = () => { const result = createApplication({ job: selected, answers }); if (result.error) return setMessage(result.error); setMessage("Application submitted. Your DFS score will appear on My Applications."); };
  return <div className="applicant-wrap"><div className="page-head"><div><h1>Browse Jobs</h1><p>Find a role and review your match before applying.</p></div></div><SearchInput value={q} onChange={setQ} placeholder="Search jobs..." /><div className="jobs-grid">{list.map(j => { const applied = applications.some(a => a.jobId === j.id && a.applicantId === user?.id); return <Card key={j.id}><Badge tone="info">OPEN</Badge><h2>{j.title}</h2><p>{j.department} · {j.location}</p><div className="match-row"><ScoreRing value={calculateMatchScore(j,user)} /><div><b>Estimated match</b><p>Based on your current profile</p></div></div><Button disabled={applied} onClick={() => openApply(j)}>{applied ? "Already applied" : "View job & Apply"}</Button></Card>; })}</div>
    <Modal open={!!selected} title={selected?.title} onClose={() => setSelected(null)} footer={step < 3 ? <><Button variant="secondary" onClick={() => step === 1 ? setSelected(null) : setStep(step - 1)}>Back</Button><Button onClick={() => setStep(step + 1)}>Continue <ChevronRight size={16} /></Button></> : <><Button variant="secondary" onClick={() => setStep(2)}>Back</Button><Button onClick={submit}>Submit application</Button></>}>{message ? <div className="center"><CheckCircle2 size={40} /><h3>{message}</h3><Button onClick={() => setSelected(null)}>Done</Button></div> : <>{step === 1 && <div><h4>Step 1 · Review profile</h4><p>Your current profile and CV data will be submitted with this application.</p><div className="profile-card simple"><div className="avatar">S</div><div><b>Sara Ahmed</b><p>3 years · Bachelor's Degree</p><div className="tags"><Badge>React.js</Badge><Badge>JavaScript</Badge></div></div></div></div>}{step === 2 && <div><h4>Step 2 · Screening questions</h4><label>How many years have you worked with the main skill?<input value={answers[0]} onChange={e => setAnswers([e.target.value, answers[1]])} /></label><label>Why are you interested in this role?<textarea value={answers[1]} onChange={e => setAnswers([answers[0], e.target.value])} rows="4" /></label><p className="muted">Answers are for manual review and do not affect the DFS calculation.</p></div>}{step === 3 && <div><h4>Step 3 · Review & submit</h4><p>{selected?.title}</p><p>{selected?.department} · {selected?.location}</p><div className="center"><ScoreRing value={selected ? calculateMatchScore(selected,user) : 0} size="lg" /><p>Estimated match before applying</p></div><p>Submit to start the DFS calculation.</p></div>}</>}</Modal>
  </div>;
}

export function MyApplications() {
  const { applications, withdrawApplication, confirmInterview, requestReschedule, declineInterview, user } = useApp(); const [selected, setSelected] = useState(null); const [reason, setReason] = useState("Personal reason");
  const mine = applications.filter(a => !a.applicantId || a.applicantId === user?.id);
  return <div className="applicant-wrap"><div className="page-head"><div><h1>My Applications</h1><p>Track every application and see your feedback.</p></div></div><div className="jobs-grid">{mine.map(a => <Card key={a.id}><div className="card-head"><Badge tone={a.status === "Rejected" ? "danger" : a.status === "Withdrawn" ? "neutral" : a.status === "Closed" ? "danger" : "info"}>{a.status}</Badge><ScoreRing value={a.score || 0} /></div><h3>{a.jobTitle}</h3><p>{a.company}</p><div className="tracker">{["Applied", "Screening", "Interview", "Offer"].map(s => <span className={a.stage === s || ["Applied", "Screening", "Interview", "Offer"].indexOf(s) < ["Applied", "Screening", "Interview", "Offer"].indexOf(a.stage) ? "done" : ""} key={s}><i />{s}</span>)}</div>{a.interview && <Card className="interview-card"><b>Interview</b><p>{a.interview.date} · {a.interview.time} · {a.interview.format}</p><p>Status: {a.interview.status}</p>{a.interview.status === "Pending" && <div className="inline"><Button onClick={() => confirmInterview(a.id)}>Confirm attendance</Button><Button variant="secondary" onClick={() => requestReschedule(a.id, "Please suggest another slot.")}>Request reschedule</Button><Button variant="danger" onClick={() => declineInterview(a.id)}>Decline invitation</Button></div>}</Card>}<div className="inline"><Button variant="secondary" onClick={() => setSelected(a)}>View details</Button>{["Under Review", "Pending"].includes(a.status) && <Button variant="danger" onClick={() => { withdrawApplication(a.id, "Personal reason"); }}>Withdraw application</Button>}</div></Card>)}</div>
    <Modal open={!!selected} title={selected?.jobTitle} onClose={() => setSelected(null)}><div className="center"><ScoreRing value={selected?.score || 0} size="lg" /><h3>{selected?.status}</h3></div><h4>Score breakdown</h4>{[["Skills", 45], ["Experience", 70], ["Qualifications", 62], ["Custom/Fit", 58]].map(x => <div className="dimension" key={x[0]}><div><span>{x[0]}</span><b>{x[1]}%</b></div><i style={{ width: `${x[1]}%` }} /></div>)}{(selected?.updates || []).length > 0 && <><h4>Application Updates</h4><div className="updates-list">{selected.updates.map(u => <div className="update-item" key={u.id}><b>{u.text}</b><small>{new Date(u.at).toLocaleString()}</small></div>)}</div></>}{selected?.feedback && <Card className="feedback"><b>Feedback</b><p>{selected.feedback}</p><p>Add skills that match your target roles to improve future scores.</p></Card>}{selected?.status === "Withdrawn" && <p>Your withdrawal is recorded for analytics. You cannot re-apply to this same posting.</p>}</Modal>
  </div>;
}

export function ApplicantProfile() {
  const { user, updateProfile } = useApp(); const [name, setName] = useState(user.name || "Sara Ahmed"); const [email, setEmail] = useState(user.email || "sara@example.com"); const [skills, setSkills] = useState(user.skills || ["React.js", "JavaScript", "Figma"]); const [skill, setSkill] = useState(""); const [saved, setSaved] = useState(false);
  const save = () => { updateProfile({ name, email, skills }); setSaved(true); setTimeout(() => setSaved(false), 1500); };
  return <div className="applicant-wrap"><Card><div className="profile-card simple"><div className="avatar xl">A</div><div><h1>Applicant Profile</h1><p>Keep your profile current so match scores reflect your skills.</p></div></div><label>Full Name<input value={name} onChange={e => setName(e.target.value)} /></label><label>Email<input value={email} onChange={e => setEmail(e.target.value)} /></label><label>CV / Resume<div className="upload"><FileText size={18} /> Upload or replace CV</div></label><h3>Skills</h3><div className="tag-input">{skills.map(s => <span className="tag" key={s}>{s}<button onClick={() => setSkills(skills.filter(x => x !== s))}>×</button></span>)}<input value={skill} onChange={e => setSkill(e.target.value)} placeholder="Add skill" onKeyDown={e => { if (e.key === "Enter" && skill.trim() && !skills.includes(skill.trim())) { setSkills([...skills, skill.trim()]); setSkill(""); } }} /></div>{saved && <div className="success-pill">Profile saved. Match previews will use the new skills.</div>}<Button onClick={save}>Save profile</Button></Card></div>;
}
